AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/AbcSize:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 60

Metrics/ParameterLists:
  Max: 20

Lint/MissingSuper:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Max: 160

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false
