AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - lib/discorb/emoji_table.rb

inherit_gem:
  syntax_tree: config/rubocop.yml

require:
- rubocop-rake
- rubocop-rspec

Naming/VariableNumber:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false