# A new wrapper for the Discorb API.
#
# @author sevenc-nanashi
module Discorb
  Colour: singleton(Discorb::Color)
  API_BASE_URL: String
  VERSION: String
  VERSION_ARRAY: Array[Numeric]
  USER_AGENT: String
  Unset: untyped
end
