module Discorb
  #
  # Represents a category in a guild.
  class CategoryChannel < Discorb::GuildChannel
    include Discorb::ChannelContainer

    def channels: () -> Array[Discorb::GuildChannel]

    def create_text_channel: (
                               String name,
                               ?topic: String?,
                               ?rate_limit_per_user: Numeric?,
                               ?slowmode: Numeric?,
                               ?position: Numeric?,
                               ?nsfw: bool?,
                               ?permission_overwrites: Hash[Discorb::Role | Discorb::Member, Discorb::PermissionOverwrite]?,
                               ?parent: Discorb::CategoryChannel?,
                               ?reason: String?
                             ) -> Async::Task[Discorb::TextChannel]

    def create_voice_channel: (
                                String name,
                                ?bitrate: Numeric,
                                ?user_limit: Numeric?,
                                ?position: Numeric?,
                                ?permission_overwrites: Hash[Discorb::Role | Discorb::Member, Discorb::PermissionOverwrite]?,
                                ?parent: Discorb::CategoryChannel?,
                                ?reason: String?
                              ) -> Async::Task[Discorb::VoiceChannel]

    def create_news_channel: (
                               String name,
                               ?topic: String?,
                               ?rate_limit_per_user: Numeric?,
                               ?slowmode: Numeric?,
                               ?position: Numeric?,
                               ?nsfw: bool?,
                               ?permission_overwrites: Hash[Discorb::Role | Discorb::Member, Discorb::PermissionOverwrite]?,
                               ?parent: Discorb::CategoryChannel?,
                               ?reason: String?
                             ) -> Async::Task[Discorb::NewsChannel]

    def create_stage_channel: (
                                String name,
                                ?bitrate: Numeric,
                                ?position: Numeric?,
                                ?permission_overwrites: Hash[Discorb::Role | Discorb::Member, Discorb::PermissionOverwrite]?,
                                ?parent: Discorb::CategoryChannel?,
                                ?reason: String?
                              ) -> Async::Task[Discorb::StageChannel]
  end
end
