module Discorb
  #
  # Module for container of channels.
  module ChannelContainer
    #
    # Returns text channels.
    #
    # @return [Array<Discorb::TextChannel>] The text channels.
    def text_channels: -> ::Array[Discorb::TextChannel]

    #
    # Returns voice channels.
    #
    # @return [Array<Discorb::VoiceChannel>] The voice channels.
    def voice_channels: -> ::Array[Discorb::VoiceChannel]

    #
    # Returns news channels.
    #
    # @return [Array<Discorb::NewsChannel>] The news channels.
    def news_channels: -> ::Array[Discorb::NewsChannel]

    #
    # Returns stage channels.
    #
    # @return [Array<Discorb::StageChannel>] The stage channels.
    def stage_channels: -> ::Array[Discorb::StageChannel]
  end
end
