module Discorb
  #
  # @abstract
  # Represents Discord model.
  class DiscordModel
    def eql?: (untyped other) -> bool

    def ==: (untyped other) -> untyped

    %a{pure}
    def inspect: -> String

    # @private
    %a{pure}
    def hash: -> untyped
  end
end
