module Discorb
  type emoji = Discorb::Emoji | Discorb::PartialEmoji

  # Represents a Discord emoji.
  # @abstract
  class Emoji
    def eql?: (untyped other) -> bool

    def ==: (untyped other) -> untyped

    %a{pure}
    def inspect: -> String
  end
end
