module Discorb
  type emoji = Discorb::Emoji | Discorb::PartialEmoji
  # Represents a Discord emoji.
  # @abstract
  class Emoji
    def eql?: (untyped other) -> bool

    def ==: (untyped other) -> untyped

    def inspect: () -> untyped
  end
end
