name: Run spec

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
        os:
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          bundle install
      - name: Run spec
        if: "!(matrix.os == 'windows-latest' && matrix.ruby-version == '3.1')" # https://github.com/socketry/async/issues/206
        run: bundle exec rake spec
