name: Run spec

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        ruby-version:
          - "3.1"
          - "3.2"
        os:
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          bundle install
      - name: Run spec (Parallel)
        if: matrix.os == 'ubuntu-latest'
        run: bundle exec rake spec
      - name: Run spec (Non-parallel)
        if: matrix.os == 'windows-latest'
        run: bundle exec rspec spec/*.spec.rb spec/**/*.spec.rb
